---
- name: Check if YAY is already installed
  changed_when: '"/usr/bin/yay" not in g_yay_check.stdout'
  failed_when: false
  register: g_yay_check
  ansible.builtin.command:
    cmd: >-
      arch-chroot /mnt which yay

- name: Block for yay installation
  when: '("/usr/bin/yay" not in g_yay_check.stdout) and yay_enabled == "true"'
  block:
    - name: Allow temporary passwordless sudo for setup user
      ansible.builtin.copy:
        dest: "/mnt/etc/sudoers.d/99-{{ setup_username }}-temp"
        content: "{{ setup_username }} ALL=(ALL) NOPASSWD: ALL\n"
        owner: root
        group: root
        mode: "0440"

    - name: Clone yay
      ansible.builtin.command:
        cmd: >-
          arch-chroot /mnt sudo -u {{ setup_username }}
          git clone https://aur.archlinux.org/yay.git /home/{{ setup_username }}/yay

    - name: Build and install yay
      ansible.builtin.command:
        cmd: >-
          arch-chroot /mnt bash -c 'cd /home/{{ setup_username }}/yay &&
          sudo -u {{ setup_username }} makepkg -si --noconfirm'

    - name: Remove yay build dir
      ansible.builtin.file:
        path: /mnt/home/{{ setup_username }}/yay
        state: absent

    - name: Remove temporary passwordless sudo
      ansible.builtin.file:
        path: "/mnt/etc/sudoers.d/99-{{ setup_username }}-temp"
        state: absent
