---
- name: Prepare Facts
  hosts: all
  gather_facts: false
  tags: always
  # vars_prompt:
  #   - name: luks_passhrase
  #     prompt: "Enter LUKS passphrase"
  #     private: true
  #   - name: setup_username
  #     prompt: "Enter desired username"
  #     private: false
  #   - name: setup_password
  #     prompt: "Enter desired password"
  #     private: true
  #   - name: hostname
  #     prompt: "Enter system hostname"
  #     private: false
  #   - name: diskdevice
  #     prompt: "What is the disk designation? (i.e. nvm0n1)"
  #     private: false
  tasks:
    - name: Cache variables for next play
      ansible.builtin.set_fact:
        cacheable: true
        luks_passhrase: "{{ luks_passhrase }}"
        setup_username: "{{ setup_username }}"
        setup_password: "{{ setup_password }}"
        hostname: "{{ hostname }}"
        diskdevice: "{{ diskdevice }}"
        userspace: "{{ userspace }}"

- name: Arch BTRFS installation into VM
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Gather facts
      ansible.builtin.setup:
  roles:
    - a_filesystems
    - b_arch_initial
    - c_hostname
    - d_locale
    - e_user
    - fa_bootloader
    - fb_mkinitcpio
    - g_yay
    - i_reboot

- name: After reboot playbook
  hosts: all
  gather_facts: false
  tags: afterreboot
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: "{{ setup_username }}"
    ansible_ssh_private_key_file: roles/e_user/files/id_25519_installer
  roles:
    - j_afterreboot
    - k_userspace
    - l_darkmode
    - z_cleanup
