---
- name: Prepare Facts
  hosts: all
  gather_facts: false
  tasks:
    - name: If afterreboot
      tags: never, afterreboot
      ansible.builtin.set_fact:
        ansible_user: "{{ setup_username }}"

    - name: Gather hardware facts
      tags: always
      ansible.builtin.setup:
        gather_subset:
          - hardware

    - name: Cache variables
      tags: always
      ansible.builtin.set_fact:
        cacheable: true
        luks_passhrase: "{{ luks_passhrase }}"
        setup_username: "{{ setup_username }}"
        setup_password: "{{ setup_password }}"
        hostname: "{{ inventory_hostname_short }}"
        userspace: "{{ userspace }}"
        diskdevice: >-
          {{
              ansible_facts['devices']
              | dict2items
              | selectattr('value.serial', 'defined')
              | selectattr('value.serial', 'equalto', diskserial)
              | map(attribute='key')
              | first
          }}


- name: Arch BTRFS installation into VM
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Gather all facts
      ansible.builtin.setup:
  roles:
    - a_filesystems
    - b_arch_initial
    - c_hostname
    - d_locale
    - e_user
    - fb_mkinitcpio
    - fa_bootloader
    - g_yay
    - i_reboot

- name: After reboot playbook
  hosts: all
  gather_facts: false
  tags: afterreboot
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: "{{ setup_username }}"
    ansible_ssh_private_key_file: roles/e_user/files/id_25519_installer
  roles:
    - j_afterreboot
    - k_userspace
    - l_darkmode
    - z_cleanup
