---
- name: Run reflector for local mirrors
  changed_when: false
  ansible.builtin.command:
    cmd: >-
      reflector --country "Netherlands" --age 6 --sort rate --save /etc/pacman.d/mirrorlist

- name: Install base system with pacstrap
  ansible.builtin.command:
    cmd: >-
      pacstrap -K /mnt
      base linux linux-firmware
      btrfs-progs vim networkmanager sudo
      openssh cryptsetup base-devel git htop btop
  args:
    creates: /mnt/etc/arch-release

- name: Generate fstab
  ansible.builtin.command:
    cmd: genfstab -pU /mnt
  register: fstab_out
  changed_when: false

- name: Write fstab
  ansible.builtin.copy:
    dest: /mnt/etc/fstab
    content: "{{ fstab_out.stdout }}\n"
    mode: "0644"

- name: Set MAKEFLAGS in makepkg.conf
  ansible.builtin.replace:
    path: /mnt/etc/makepkg.conf
    regexp: '^#MAKEFLAGS="-j2"$'
    replace: 'MAKEFLAGS="-j4"'


- name: Enable NetworkManager
  changed_when: false
  ansible.builtin.command:
    cmd: arch-chroot /mnt systemctl enable NetworkManager
