---
- name: Set UID in facts
  tags: always
  ansible.builtin.set_fact:
    k_userspace_uid: "{{ j_afterreboot_uid }}"

- name: Run stow installation
  tags: stow
  ansible.builtin.include_tasks:
    file: stow.yml
    apply:
      tags: stow

- name: Run sddm-dekstop
  when: userspace == 'plasma'
  ansible.builtin.include_tasks:
    file: sddm-desktop.yml

- name: Install sway and user environment
  tags: sway
  when: userspace == 'sway'
  ansible.builtin.include_tasks:
    file: sway.yml
    apply:
      tags: sway

- name: Run zsh installation
  tags: zsh
  ansible.builtin.include_tasks:
    file: zsh.yml
    apply:
      tags: zsh

- name: Run flatpak installation
  tags: flatpak
  ansible.builtin.include_tasks:
    file: flatpak.yml
    apply:
      tags: flatpak
