---
- name: Install SDDM and Plasma-desktop
  ansible.builtin.command:
    cmd: >-
      arch-chroot /mnt pacman --noconfirm -S
      sddm
      plasma-meta
      dolphin
      konsole

- name: Install packages
  community.general.pacman:
    name:
      - sddm
      - plasma-meta
      - dolphin
      - konsole
    state: present
    config: /etc/pacman.conf
    update_cache: true

- name: Place SDDM conf file
  ansible.builtin.copy:
    mode: "0644"
    dest: /etc/sddm.conf
    content: |
      [General]
      DisplayServer=wayland

      [Wayland]
      CompositorCommand=/usr/bin/kwin_wayland
      SessionCommand=/usr/share/sddm/scripts/wayland-session
      SessionDir=/usr/share/wayland-sessions

      [Theme]
      Current=breeze

- name: Create kdeglobals for user
  ansible.builtin.file:
    path: /home/{{ setup_username }}/.config/kdedefaults
    mode: "0755"
    state: directory

- name: Set kdeglobals to breeze
  ansible.builtin.copy:
    mode: "0600"
    dest: /home/{{ setup_username }}/.config/kdedefaults/kdeglobals
    owner: 1000
    group: 1000
    content: |
      [General]
      ColorScheme=BreezeDark

      [Icons]
      Theme=breeze-dark

      [KDE]
      widgetStyle=Breeze

- name: Enable sddm service
  ansible.builtin.systemd_service:
    name: sddm
    enabled: true
