---
- name: Install packages
  community.general.pacman:
    name:
      - sway
      - swaybg
      - swayidle
      - swaylock
      - swayosd
      - waybar
      - wmenu
      - kitty
      - fastfetch
      - j4-dmenu-desktop
      - mako
      - neovim
      - gnome-keyring
      - seahorse
      - wl-clipboard
      - slurp
      - otf-font-awesome
      - ttf-jetbrains-mono
      - ttf-jetbrains-mono-nerd
      - greetd
      - greetd-tuigreet
      - thunar
      - galculator
      - grim
      - rclone
    state: present
    update_cache: false

- name: Create background directory
  ansible.builtin.file:
    path: /usr/share/backgrounds
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Deploy background into place
  ansible.builtin.copy:
    src: arch-background.jpg
    dest: /usr/share/backgrounds/arch-background.jpg
    owner: root
    group: root
    mode: "0644"

- name: Deploy greetd config
  ansible.builtin.copy:
    mode: "0644"
    owner: root
    group: root
    dest: /etc/greetd/config.toml
    content: |
      [terminal]
      vt = 1
      [default_session]
      command = "tuigreet -r --cmd 'sway --unsupported-gpu'"
      user = "greeter"

- name: Enable greetd login
  register: k_userspace_greetd
  ansible.builtin.systemd:
    name: greetd
    enabled: true

- name: Write username to greetd
  ansible.builtin.copy:
    content: "{{ setup_username }}"
    dest: "/var/cache/tuigreet/lastuser"
    mode: "0644"
    owner: "greeter"
    group: "greeter"

- name: Set display output for sway
  ansible.builtin.copy:
    content: "{{ sway_display }}"
    dest: "/etc/sway/config.d/10-display.conf"
    mode: "0644"
    owner: root
    group: root

- name: Set mod key bind
  ansible.builtin.copy:
    content: "{{ sway_modkey }}"
    dest: "/etc/sway/config.d/20-modkey.conf"
    mode: "0644"
    owner: root
    group: root
