---
- name: Install systemd-boot
  ansible.builtin.command:
    cmd: arch-chroot /mnt bootctl install --esp-path /efi --boot-path /boot

- name: Write loader.conf
  ansible.builtin.copy:
    dest: /mnt/efi/loader/loader.conf
    content: |
      default arch-linux.efi
      timeout 3
      editor no
    owner: root
    group: root
    mode: "0644"
