---
- name: Install systemd-boot
  ansible.builtin.command:
    cmd: arch-chroot /mnt bootctl install --esp-path /efi --boot-path /boot

- name: Include tasks for secure boot
  ansible.builtin.import_tasks:
    file: secure_boot.yml

- name: Write loader.conf
  ansible.builtin.copy:
    dest: /mnt/efi/loader/loader.conf
    content: |
      default arch-linux.efi
      timeout 3
      editor no
    owner: root
    group: root
    mode: "0644"

- name: Force notified handlers to run now
  ansible.builtin.meta: flush_handlers
