---
- name: Set hostname
  ansible.builtin.copy:
    mode: "0644"
    dest: /mnt/etc/hostname
    content: "{{ hostname }}\n"

- name: Add hostname entry to hosts
  ansible.builtin.lineinfile:
    mode: "0644"
    path: /mnt/etc/hosts
    line: '127.0.1.1       {{ hostname }}.domain.local      {{ hostname }}'
    state: present
    create: true
