---
- name: Remove installer identity
  ansible.builtin.file:
    state: absent
    path: "/home/{{ setup_username }}/.ssh/{{ item }}"
  loop:
    - { id_25519_installer }
    - { id_25519_installer.pub }

- name: Ask for confirmation
  ansible.builtin.pause:
    prompt: "Do you want to reboot? (yes/no)"
  register: z_cleanup_reboot_confirm

- name: Abort if not confirmed
  ansible.builtin.fail:
    msg: "Reboot aborted by user"
  when: z_cleanup_reboot_confirm.user_input | lower != "yes"

- name: Reboot machine
  ansible.builtin.command:
    cmd: reboot now
  async: 1
  poll: 0

- name: Send message
  ansible.builtin.debug:
    msg: "System wil reboot now, please enter LUKS password"
